2021-05-27 12:05:43,621 INFO    MainThread:32458 [wandb_setup.py:_flush():69] setting env: {}
2021-05-27 12:05:43,621 INFO    MainThread:32458 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 12:05:43,621 INFO    MainThread:32458 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_init.py:_log_setup():336] Logging user logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_120543-9pok8qnd/logs/debug.log
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_init.py:_log_setup():337] Logging internal logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_120543-9pok8qnd/logs/debug-internal.log
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_init.py:init():369] calling init triggers
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-27 12:05:43,622 INFO    MainThread:32458 [wandb_init.py:init():418] starting backend
2021-05-27 12:05:43,622 INFO    MainThread:32458 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-27 12:05:43,632 INFO    MainThread:32458 [backend.py:ensure_launched():132] starting backend process...
2021-05-27 12:05:43,641 INFO    MainThread:32458 [backend.py:ensure_launched():136] started backend process with pid: 32491
2021-05-27 12:05:43,642 INFO    MainThread:32458 [wandb_init.py:init():423] backend started and connected
2021-05-27 12:05:43,644 INFO    MainThread:32458 [wandb_init.py:init():465] updated telemetry
2021-05-27 12:05:43,645 INFO    MainThread:32458 [wandb_init.py:init():484] communicating current version
2021-05-27 12:05:44,272 INFO    MainThread:32458 [wandb_init.py:init():489] got version response 
2021-05-27 12:05:44,272 INFO    MainThread:32458 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-27 12:05:44,497 INFO    MainThread:32458 [wandb_init.py:init():522] starting run threads in backend
2021-05-27 12:05:45,794 INFO    MainThread:32458 [wandb_run.py:_console_start():1565] atexit reg
2021-05-27 12:05:45,795 INFO    MainThread:32458 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-27 12:05:45,795 INFO    MainThread:32458 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-27 12:05:45,796 INFO    MainThread:32458 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-27 12:05:45,797 INFO    MainThread:32458 [wandb_init.py:init():546] run started, returning control to user process
2021-05-27 12:05:45,797 INFO    MainThread:32458 [wandb_config.py:__setitem__():141] config set epochs = 3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fbce87e90a0>>
2021-05-27 12:05:45,797 INFO    MainThread:32458 [wandb_run.py:_config_callback():787] config_cb epochs 3 None
2021-05-27 12:05:45,797 INFO    MainThread:32458 [wandb_config.py:__setitem__():141] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fbce87e90a0>>
2021-05-27 12:05:45,798 INFO    MainThread:32458 [wandb_run.py:_config_callback():787] config_cb batch_size 32 None
2021-05-27 12:06:01,877 INFO    MainThread:32458 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-27 12:06:01,878 INFO    MainThread:32458 [wandb_run.py:_restore():1507] restore
2021-05-27 12:06:03,882 INFO    MainThread:32458 [wandb_run.py:_restore():1507] restore
2021-05-27 12:06:06,326 ERROR   MainThread:32458 [wandb_run.py:_atexit_cleanup():1553] Problem finishing run
Traceback (most recent call last):
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1543, in _atexit_cleanup
    self._on_finish()
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1695, in _on_finish
    print("")
BrokenPipeError: [Errno 32] Broken pipe
