2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_init.py:_log_setup():336] Logging user logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210528_173420-33g2rdpr/logs/debug.log
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_init.py:_log_setup():337] Logging internal logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210528_173420-33g2rdpr/logs/debug-internal.log
2021-05-28 17:34:20,441 INFO    MainThread:17453 [wandb_init.py:init():369] calling init triggers
2021-05-28 17:34:20,442 INFO    MainThread:17453 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-28 17:34:20,442 INFO    MainThread:17453 [wandb_init.py:init():418] starting backend
2021-05-28 17:34:20,442 INFO    MainThread:17453 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 17:34:20,450 INFO    MainThread:17453 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 17:34:20,456 INFO    MainThread:17453 [backend.py:ensure_launched():136] started backend process with pid: 17489
2021-05-28 17:34:20,458 INFO    MainThread:17453 [wandb_init.py:init():423] backend started and connected
2021-05-28 17:34:20,460 INFO    MainThread:17453 [wandb_init.py:init():465] updated telemetry
2021-05-28 17:34:20,460 INFO    MainThread:17453 [wandb_init.py:init():484] communicating current version
2021-05-28 17:34:21,068 INFO    MainThread:17453 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 17:34:21,069 INFO    MainThread:17453 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 17:34:21,495 INFO    MainThread:17453 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 17:34:21,590 WARNING MainThread:17453 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 799, in communicate_run_start
    result = self._communicate(rec)
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
